add brew checks

diff --git a/src/.chezmoiscripts/run_onchange_before_04_op.sh.tmpl b/src/.chezmoiscripts/run_onchange_before_04_op.sh.tmpl
--- a/src/.chezmoiscripts/run_onchange_before_04_op.sh.tmpl
+++ b/src/.chezmoiscripts/run_onchange_before_04_op.sh.tmpl
@@ -6,6 +6,17 @@ if ! command -v op &> /dev/null; then
     ARCH="amd64"
     OP_VERSION="v$(curl https://app-updates.agilebits.com/check/1/0/CLI2/en/2.0.0/N -s | grep -Eo '[0-9]+\.[0-9]+\.[0-9]+')"
 
+    # Check if 'brew' is not available
+    if ! command -v brew &> /dev/null; then
+        eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
+    fi
+
+    # Check if 'unzip' is not available
+    if ! command -v unzip &> /dev/null; then
+        print_error "Error: 'unzip' command not found. Please install 'unzip' before proceeding."
+        exit 1
+    fi
+
     # Download and install 1Password CLI
     curl -sSfo op.zip \
         https://cache.agilebits.com/dist/1P/op2/pkg/"$OP_VERSION"/op_linux_"$ARCH"_"$OP_VERSION".zip \
