update op.sh

diff --git a/src/.chezmoiscripts/run_onchange_before_05_op.sh.tmpl b/src/.chezmoiscripts/run_onchange_before_05_op.sh.tmpl
--- a/src/.chezmoiscripts/run_onchange_before_05_op.sh.tmpl
+++ b/src/.chezmoiscripts/run_onchange_before_05_op.sh.tmpl
@@ -6,38 +6,48 @@ if ! command -v op &> /dev/null; then
     ARCH="amd64"
     OP_VERSION="v$(curl https://app-updates.agilebits.com/check/1/0/CLI2/en/2.0.0/N -s | grep -Eo '[0-9]+\.[0-9]+\.[0.9]+')"
 
-    # Check if 'brew' is not available
-    if ! command -v brew &> /dev/null; then
-        eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
-    fi
-
     # Check if 'unzip' is not available
     if ! command -v unzip &> /dev/null; then
-        print_error "Error: 'unzip' command not found. Please install 'unzip' before proceeding."
+        echo "Error: 'unzip' command not found. Please install 'unzip' before proceeding."
         exit 1
     fi
 
-    # Set the installation directory to a user-writable location
-    INSTALL_DIR="$HOME/.local/bin"
+    # Use the system's temporary directory for unzipping
+    TMP_DIR="/tmp/1password_install"
 
-    # Create the installation directory if it doesn't exist
-    mkdir -p "$INSTALL_DIR"
+    # Create the temporary directory if it doesn't exist
+    mkdir -p "$TMP_DIR"
 
-    # Download and install 1Password CLI
-    curl -sSfo "$INSTALL_DIR/op.zip" \
-        https://cache.agilebits.com/dist/1P/op2/pkg/"$OP_VERSION"/op_linux_"$ARCH"_"$OP_VERSION".zip \
-        && unzip -oq -d "$INSTALL_DIR" "$INSTALL_DIR/op.zip" \
-        && rm "$INSTALL_DIR/op.zip"
+    # Download and unzip 1Password CLI in the temporary directory
+    curl -sSfo "$TMP_DIR/op.zip" \
+        https://cache.agilebits.com/dist/1P/op2/pkg/"$OP_VERSION"/op_linux_"$ARCH"_"$OP_VERSION".zip
+    unzip -oq -d "$TMP_DIR" "$TMP_DIR/op.zip"
+    rm "$TMP_DIR/op.zip"
 
-    # Check if the installation was successful
+    # Check if the unzip was successful
     if [ $? -eq 0 ]; then
-        print_success "1Password CLI installed to $INSTALL_DIR."
+        echo "1Password CLI files unzipped to $TMP_DIR."
+
+        # Move the files to the system-wide location with sudo
+        sudo mv "$TMP_DIR/op" /usr/local/bin/
+        sudo mv "$TMP_DIR/op.sig" /usr/local/bin/
+
+        # Check if the move was successful
+        if [ $? -eq 0 ]; then
+            echo "1Password CLI installed to /usr/local/bin."
+        else
+            echo "Failed to move 1Password CLI to /usr/local/bin."
+            exit 1
+        fi
     else
-        print_error "Failed to install 1Password CLI."
+        echo "Failed to unzip 1Password CLI."
         exit 1
     fi
+
+    # Clean up the temporary directory
+    rm -rf "$TMP_DIR"
 else
-    print_success "1Password CLI is already installed."
+    echo "1Password CLI is already installed."
 fi
 
 # Check if op config file exists and create it if it doesn't. Check if the operation was successful.
